#!/bin/bash
set -e

# UFC Whale Dashboard - Fetch holders data for all UFC fights
# Cron: 40 * * * * /Users/pablo/Code/polymarket-bots/my-ufc-whale-dashboard/cron_run.sh

cd "$(dirname "$0")"

LOG_DIR="$(pwd)/data/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/run_$(date +"%Y%m%d_%H%M%S").log"
exec > >(tee "$LOG_FILE")
exec 2> >(tee -a "$LOG_FILE" >&2)
echo "Logging to $LOG_FILE"

export PYTHONUNBUFFERED=1

# Use explicit Python path for cron compatibility.
PYTHON="/Users/pablo/.pyenv/shims/python"

# 1. Fetch live volume data for all active UFC markets
echo "Starting Volume Fetch..."
chmod +x get_market_current_holdings.sh
./get_market_current_holdings.sh

# 2. Fetch ticket counts
echo "Starting Ticket Count Fetch..."
"$PYTHON" -u utils/fetch_ufc_ticket_counts.py

# 3. Fetch holders data
echo "Starting Holders Fetch..."
RUN_MARKER=$(mktemp data/.run_marker.XXXXXX)
trap 'rm -f "$RUN_MARKER"' EXIT
"$PYTHON" -u utils/fetch_ufc_holders.py

# 4. After scraping, run the report on the latest CSV
LATEST_CSV=$(find data -maxdepth 1 -type f -name "ufc_holders_*.csv" ! -name "*_pnl.csv" -newer "$RUN_MARKER" | sort | tail -1)
LATEST_PNL_CSV=""
if [ -n "$LATEST_CSV" ]; then
  echo "Running report on $LATEST_CSV"
  "$PYTHON" -u report_ufc_holders.py "$LATEST_CSV"
  LATEST_PNL_CSV="${LATEST_CSV%.csv}_pnl.csv"
else
  echo "No CSV found to report on."
fi

# 5. Copy files to Dashboard
# Auto-detect path: use the Mac path first, then Raspberry Pi path if present.
if [ -d "/Users/pablo/Code/mma-ai/Streamlit/data/whale_data" ]; then
  DEST_DIR="/Users/pablo/Code/mma-ai/Streamlit/data/whale_data"
elif [ -d "$HOME/mma-ai/Streamlit/data/whale_data" ]; then
  DEST_DIR="$HOME/mma-ai/Streamlit/data/whale_data"
elif [ -d "/Users/td/Code/mma-ai/Streamlit/data/whale_data" ]; then
  DEST_DIR="/Users/td/Code/mma-ai/Streamlit/data/whale_data"
else
  echo "Warning: Streamlit data directory not found. Skipping copy."
  DEST_DIR=""
fi

if [ -n "$DEST_DIR" ]; then
  echo "Copying files to $DEST_DIR"
  mkdir -p "$DEST_DIR"
  
  # Copy the PnL CSV generated by this run.
  if [ -f "$LATEST_PNL_CSV" ]; then
      cp "$LATEST_PNL_CSV" "$DEST_DIR"
      echo "Copied latest PnL CSV."
  else
      echo "No latest PnL CSV found to copy."
  fi
  
  # Copy Volume Data
  if [ -f "data/all_ufc_volumes.json" ]; then
      cp "data/all_ufc_volumes.json" "$DEST_DIR"
      echo "Copied volume data."
  else
      echo "Warning: data/all_ufc_volumes.json not found."
  fi
  
  # Copy Ticket Count Data
  if [ -f "data/all_ufc_ticket_counts.json" ]; then
      cp "data/all_ufc_ticket_counts.json" "$DEST_DIR"
      echo "Copied ticket count data."
  else
      echo "Warning: data/all_ufc_ticket_counts.json not found."
  fi
fi

echo "Run complete."
